apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrong-quota-memory
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
     metadata:
       labels:
         app: my-app
     spec:
       containers:
       - name: my-app
         image: dockerpac/docker-demo:1
         resources:
           limits: 
             cpu: "100m"
             memory: "600Mi"
           requests:
             cpu: "10m"
             memory: "100Mi"
