apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 10
  template:
     metadata:
       labels:
         app: my-app
     spec:
       containers:
       - name: my-app
         image: dockerpac/docker-demo:1
         resources:
           limits: 
             cpu: "2000m"
             memory: "300Mi"
           requests:
             cpu: "2000m"
             memory: "300Mi"
