apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminating
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 2
  template:
     metadata:
       labels:
         app: my-app
     spec:
       containers:
       - name: my-app
         image: dockerpac/docker-demo:1
         lifecycle:
           preStop:
             exec:
               command: ["/bin/sh","-c","sleep 30"]
         env:
         - name: VERSION
           value: "2"
         resources:
           limits: 
             cpu: "100m"
             memory: "800Mi"
           requests:
             cpu: "10m"
             memory: "800Mi"
