apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
spec:
  limits:
  - max:
      cpu: "2"
      memory: "8Gi"
    maxLimitRequestRatio:
      cpu: "10"
      memory: "1"
    min:
      cpu: "10m"
      memory: "100Mi"
    type: Pod
